export const colors = {
  background: '#0B0F19',
  backgroundSecondary: '#0F172A',
  muted: '#1E293B',
  border: '#334155',
  foreground: '#E2E8F0',
  foregroundMuted: '#94A3B8',
  primary: '#7C3AED',
  primaryLight: '#8B5CF6',
  primaryDark: '#6D28D9',
  onPrimary: '#FFFFFF',
  accent: '#3B82F6',
  onAccent: '#FFFFFF',
  success: '#10B981',
  successDark: '#059669',
  warning: '#F59E0B',
  danger: '#EF4444',
  dangerDark: '#DC2626',
  online: '#10B981',
  offline: '#64748B',
  error: '#EF4444',
};

export const fonts = {
  heading: 'Inter, sans-serif',
  body: 'Inter, sans-serif',
};

export const commonStyles = {
  pageContainer: {
    minHeight: '100vh',
    display: 'flex',
    backgroundColor: colors.background,
    color: colors.foreground,
    fontFamily: fonts.body,
  },
  sidebar: {
    width: '260px',
    backgroundColor: colors.backgroundSecondary,
    borderRight: `1px solid ${colors.border}`,
    display: 'flex',
    flexDirection: 'column' as const,
    position: 'fixed' as const,
    top: 0,
    left: 0,
    bottom: 0,
    zIndex: 40,
  },
  mainContent: {
    flex: 1,
    marginLeft: '260px',
    padding: '32px',
    minWidth: 0,
  },
  card: {
    backgroundColor: colors.backgroundSecondary,
    border: `1px solid ${colors.border}`,
    borderRadius: '12px',
    padding: '24px',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16px',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '8px 16px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 500,
    fontFamily: fonts.body,
    cursor: 'pointer',
    transition: 'background-color 150ms ease, opacity 150ms ease',
  },
  input: {
    backgroundColor: colors.muted,
    border: `1px solid ${colors.border}`,
    borderRadius: '8px',
    padding: '8px 12px',
    color: colors.foreground,
    fontSize: '14px',
    fontFamily: fonts.body,
    outline: 'none',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 10px',
    borderRadius: '9999px',
    fontSize: '12px',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
  },
  flexRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  flexColumn: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
};
